/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.8).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Transaction;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2019-05-29T12:43:24.827Z[GMT]")
@Api(value = "transactions", description = "the transactions API")
public interface TransactionsApi {

    @ApiOperation(value = "Create a new transaction", nickname = "createTransaction", notes = "Creates a transaction of the specified type, ammount and accounts", response = Integer.class, authorizations = {
        @Authorization(value = "cookieAuth")    }, tags={ "transaction", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Transaction created", response = Integer.class),
        @ApiResponse(code = 400, message = "Invalid input"),
        @ApiResponse(code = 403, message = "Forbidden, you do not have the required rights"),
        @ApiResponse(code = 500, message = "Oops, something went wrong on the server. Sorry!")})
    @RequestMapping(value = "/transactions",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Integer> createTransaction(@ApiParam(value = ""  )  @Valid @RequestBody Transaction body) throws ApiException;

    @ApiOperation(value = "Get transactions depending on the optional parameters; the abstinence of any parameters results in all transactions.", nickname = "getTransactions", notes = "", response = Transaction.class, responseContainer = "List", authorizations = {
        @Authorization(value = "cookieAuth")    }, tags={ "transaction", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Transaction(s) found", response = Transaction.class, responseContainer = "List"),
        @ApiResponse(code = 400, message = "Invalid input"),
        @ApiResponse(code = 403, message = "Forbidden, you do not have the required rights"),
        @ApiResponse(code = 500, message = "Oops, something went wrong on the server. Sorry!") })
    @RequestMapping(value = "/transactions",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Transaction>> getTransactions(@ApiParam(value = "The iban of the sending backaccount") @Valid @RequestParam(value = "fromIban", required = false) String fromIban, @ApiParam(value = "The iban of the receiving backaccount") @Valid @RequestParam(value = "toIban", required = false) String toIban, @ApiParam(value = "The type of transaction; transaction, deposit, withdrawal") @Valid @RequestParam(value = "Type", required = false) Transaction.TransactionType type, @ApiParam(value = "The id of the user performing the transaction") @Valid @RequestParam(value = "performedBy", required = false) Integer performedBy,  @ApiParam(value = "get the transactions where this iban is in") @Valid @RequestParam(value = "iban", required = false) String iban) throws ApiException;

//    @ApiOperation(value = "Get the a specific transaction by using it's id", nickname = "getTransactionById", notes = "", response = Transaction.class, authorizations = {
//            @Authorization(value = "ApiKeyAuth")    }, tags={ "transaction", })
//    @ApiResponses(value = {
//            @ApiResponse(code = 200, message = "succes", response = Transaction.class),
//            @ApiResponse(code = 400, message = "Nee") })
//    @RequestMapping(value = "/transactions/search/{transactionId}",
//            produces = { "application/json" },
//            method = RequestMethod.GET)
//    ResponseEntity<Transaction> getTransactionById(@Min(1)@ApiParam(value = "The id of a transaction") @Valid @RequestParam(value = "transactionId", required = true) Integer transactionId) throws ApiException;

    @ApiOperation(value = "Returns specified transaction", nickname = "getTransactionById", notes = "Returns the specified transaction", response = Transaction.class, authorizations = {
            @Authorization(value = "cookieAuth")    }, tags={ "transaction", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "succes", response = Transaction.class),
            @ApiResponse(code = 400, message = "Invalid input"),
            @ApiResponse(code = 403, message = "Forbidden, you do not have the required rights"),
            @ApiResponse(code = 500, message = "Oops, something went wrong on the server. Sorry!") })
    @RequestMapping(value = "/transactions/{transactionId}",
            produces = { "application/json" },
            method = RequestMethod.GET)
    ResponseEntity<Transaction> getTransactionById(@Min(1)@ApiParam(value = "The transaction ID",required=true, allowableValues = "") @PathVariable("transactionId") Integer transactionId) throws ApiException;

}
